### ISSUE TITLE
Add just-wait to node_modules/.bin automatically

### ISSUE THREAD

**Issue by ElegantScripting** [Download/just-wait#2]
Please add just-wait to node_modules/.bin automatically, this way we can create package.json script commands with it, without having to type the path to it.

Many other plugins do this, and it would be great if this did too.

Thanks.

**Comment by ElegantScripting** [comment]
@Download and oddly enough, even installing it globally, my OS doesn't recognize "just-wait" a command. I'm running OS X 10.11.3.

**Comment by Download** [comment]
@ElegantScripting Thanks for your interest in `just-wait`!

I think [this pull request](https://github.com/Download/just-wait/pull/1) actually solved your problem, but I apparently forgot to publish it to NPM...

Will do that right away!

**Comment by Download** [comment]
> my OS doesn't recognize "just-wait" a command. I'm running OS X 10.11.3.

Mmmm... yes I think I know why...

we should probably add a [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) to the top of the file and make sure the executable bit is set correctly in Git.

I'm on a deadline right now and because I'm on Windows myself, it will take some setting up of VMs etc to test this, making it too big a task for me to take on right now. But I think it's actually a small fix so you might want to take a stab at picking it up yourself... I'd be grateful if you did.

If you want to try this, please:
- Fork this repo
- Clone your forked version of this repo to your local machine
- Create and switch to a new branch `issue-2`
- Implement the fix
- Commit and push to GitHub
- In GitHub, press the `Pull Request` button

In the meantime I have pushed `v1.0.4` to NPM. Please try that.

**Comment by RickWong** [comment]
@Download I get this in `v1.0.4` on Mac:
<img width="708" alt="screen shot 2016-02-22 at 22 20 41" src="https://cloud.githubusercontent.com/assets/40102/13233133/8b18c49c-d9b2-11e5-965d-bf62e804d2ae.png">

I believe there's a `\r` character on the she-bang line that's not supposed to be there.

**Comment by Download** [comment]
@RickWong Can you please check `1.0.5`.
For me `1.0.4` works (on Windows) but I'm working in the blind for the unix stuff.

**Comment by ElegantScripting** [comment]
@Download @RickWong Awesome, works great on unix now.

**Comment by Download** [comment]
:+1:  Great and thanks for the feedback!
